# Ejercicios AA1

## 1. Entorno de desarrollo y librerías básicas.

### 1.1 Librería Pandas

In [3]:
import pandas as pd

# Leer el archivo anterior y mostrar el número de elementos que posee, el número de columnas y sus nombres
df = pd.read_csv('parte1/data/coches.csv')

print(f'Número de elementos: {df.size}')
print(f'Número de columnas: {df.shape[1]}')
print(f'Nombres de las columnas: {df.columns.tolist()}')

# Mostrar de las 5 primeras filas solo la marca y el modelo
print(df[['marca', 'modelo']].head())

# Obtener cuantas marcas diferentes y cuáles son
print(f'Número de marcas diferentes: {df.marca.nunique()}')
print(f'Marcas diferentes: {df.marca.unique()}')

# Mostrar los coches de la marca Opel
print(df[df.marca == 'Opel'])

# Calcular los km promedio de cada marca
print(df.groupby('marca').kms.mean())

# Sumar 1000 euros al precio de los coches de año posterior a 2015
df.loc[df.año > 2015, 'precio'] += 1000
print(df.loc[df.año > 2015])

Número de elementos: 30
Número de columnas: 6
Nombres de las columnas: ['matrícula', 'marca', 'modelo', 'año', 'kms', 'precio']
       marca  modelo
0     Toyota   Camry
1      Honda  Accord
2       Ford  Fusion
3  Chevrolet  Malibu
4     Nissan  Altima
Número de marcas diferentes: 5
Marcas diferentes: ['Toyota' 'Honda' 'Ford' 'Chevrolet' 'Nissan']
Empty DataFrame
Columns: [matrícula, marca, modelo, año, kms, precio]
Index: []
marca
Chevrolet    34987.0
Ford         22456.0
Honda        30278.0
Nissan       38163.0
Toyota       25153.0
Name: kms, dtype: float64
  matrícula      marca  modelo   año    kms  precio
0    ABC123     Toyota   Camry  2019  25153    6300
1    XYZ456      Honda  Accord  2018  30278   10000
2    DEF789       Ford  Fusion  2020  22456    5000
3    GHI012  Chevrolet  Malibu  2017  34987    8500
4    JKL345     Nissan  Altima  2016  38163    4200


### 1.2 Librería Numpy

In [4]:
import numpy as np
# Crear un vector de tamaño 10 de ceros excepto el quinto elemento que será 1.
v = np.zeros(10)
v[4] = 1
print(v)

print("--------------------")

# Crear un vector con valores entre 10 y 49.
v = np.random.randint(10,49, size=(1,10))
print(v)

print("--------------------")


# Crear una matriz de 3x3 con valores entre 0 y 8.
v = np.random.randint(0,8, size=(3,3))
print(v)

print("--------------------")

# Crear una matriz identidad de dimensiones 4x4.
v = np.eye(4)
print(v)

print("--------------------")

# Crear un array de dimensiones 3x3x3 con valores aleatorios.
v = np.random.random((3,3,3))
print(v)

print("--------------------")

# Crear una matriz de 5x5 con 1 en los bordes y 0 en el interior.
v = np.ones((5,5))
v[1:-1,1:-1] = 0
print(v)

print("--------------------")

# Crear un vector de tamaño 10 con valores aleatorios y modificar el valor máximo por 0.
v = np.random.random(10)
v[v == v.max()] = 0
print(v)

print("--------------------")

# ¿Cómo encontrar el valor más próximo a un escalar dado, en un vector?
v = np.random.randint(0, 25, size=(1,10))
print(v)
escalar = 1
v2 = np.abs(v - escalar)
print(f"El valor más cercano a {escalar} es {v.argmin()} y se encuentra en la posición {v.min()}")

print("--------------------")

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
--------------------
[[24 37 35 28 34 36 21 36 34 33]]
--------------------
[[5 6 1]
 [7 7 5]
 [3 3 0]]
--------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
--------------------
[[[0.7113909  0.73214696 0.58490255]
  [0.8162679  0.40436614 0.12324107]
  [0.07334924 0.53085159 0.38813159]]

 [[0.0825226  0.35113485 0.6426173 ]
  [0.66829214 0.64841499 0.10761291]
  [0.22900903 0.78494234 0.72677038]]

 [[0.21897038 0.14002596 0.0834931 ]
  [0.96240948 0.04149785 0.31796402]
  [0.78977595 0.7519275  0.89787099]]]
--------------------
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
--------------------
[0.84280785 0.12381519 0.28284613 0.01410256 0.63685495 0.
 0.58240003 0.02057647 0.50257836 0.46883362]
--------------------
[[15 24 11 17  2 22 10 12 19 23]]
El valor más cercano a 1 es 4 y se encuentra en la posición 2
--------------------


## 2 Preprocesado básico de datos

### Ejercicios propuestos

In [ ]:
# Utilizando los datos del archivo iris-perdidos.csv, sustituir para cada variable 
# los valores perdidos por el promedio de los valores de dicha variable.

df = pd.read_csv('parte1/data/iris-perdidos.csv', sep = ',')

for col in df.columns[:-1]:
    df[col].fillna(df[col].mean())

print(df)

# Implementar una función que acepte un array unidimensional y dos valores reales,
# minimo y maximo, y realice el escalado del array entre los valores minimo y
# maximo.

def escalar(arr, minimo, maximo):
    return (arr - arr.min()) / (arr.max() - arr.min()) * (maximo - minimo)

print(escalar(np.array([1,2,3,4,5]), 0, 1))

# Implementar una clase en Python que permita convertir valores simbólicos a nu-
# méricos. La clase además del constructor debe poseer los métodos convertir,
# convertir_inversa. El primer método admite un array con valores simbólicos
# y devuelve otro array con los valores numéricos. El segundo método debe tomar
#como entrada un array que previamente fue convertido a numérico y devolver el
# correspondiente con valores simbólicos.

class Convertidor:
    def __init__(self):
        self.mapa = {}
        self.contador = 0

    def convertir(self, arr):
        for i in arr:
            if i not in self.mapa:
                self.mapa[i] = self.contador
                self.contador += 1
        return np.array([self.mapa[i] for i in arr])

    def convertir_inversa(self, arr):
        return np.array([list(self.mapa.keys())[list(self.mapa.values()).index(i)] for i in arr])
    
c = Convertidor()
arr = np.array(['a', 'b', 'c', 'a', 'b', 'c'])
arr_num = c.convertir(arr)
print(arr_num)
arr_simb = c.convertir_inversa(arr_num)
print(arr_simb)


     sepal length  sepal width  petal length  petal width           class
0             NaN          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]
[0.   0.25 0.5  0.75 1.  ]
[0 1 2 0 1 2]
['a' 'b' 'c' 'a' 'b' 'c']
